language: minimal

branches:
  only:
    - master
    - /^\d\.\d$/

jobs:
  include:
    - stage: Unit tests
    - env: PHP=7.3
    - stage: Code quality
      script: make cs #psalm

script: make update phpunit

cache:
  directories:
    - var/
    - bin/.phpunit/
