version: '3.4'

services:
  php:
    build:
      context: ./devops/docker
      target: stage_php
    depends_on:
      - db
    volumes:
      - ./:/app:rw

  app:
    build:
      context: ./devops/docker
      target: stage_nginx
    depends_on:
      - php
    volumes:
      - ./public:/app/public:ro
    ports:
      - "8080:80"

  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - db-data:/var/lib/mysql:rw
      - ./devops/docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"

volumes:
  db-data: {}
