version: '3.7'

services:
  app:
    build:
      context: "${APP_DIR:?}/devops/docker/php"
      target: php
      args:
        image_php: "${IMAGE_PHP:?}"
        icu: "${ICU:?}"

  web:
    build:
      context: "${APP_DIR:?}/devops/environment/base"
      target: nginx
      args:
        image_nginx: "${IMAGE_NGINX:?}"
    depends_on:
      - app
