version: '3.7'

# infrastructure
x-base: &base
  context: "${APP_DIR:?}/devops/environment/base"
  args:
    image_php: "${COMPOSE_PROJECT_NAME:?}/php"
    image_phpqa: "${IMAGE_PHPQA:?}"
    image_nginx: "${IMAGE_NGINX:?}"

x-nginx: &nginx
  <<: *base
  target: nginx

# domain
x-app: &app
  build:
    <<: *base
    target: app

x-app-test: &app-test
  <<: *app
  build:
    <<: *base
    target: app-test

x-web: &web
  build: *nginx
  volumes:
    - "${APP_DIR:?}/public:/app/public:ro"

# application
services:
  app: *app
  app-test: *app-test

  web:
    <<: *web
    depends_on: [app]
