version: '3.7'

# infrastructure
x-nginx: &nginx
  ports:
    - "${NGINX_PORT:?}:80"

# domain
x-app: &app
  volumes:
    - "${APP_DIR:?}:/app:rw"

x-web: &web
  <<: *nginx
  volumes:
    - "${APP_DIR:?}/public:/app/public:ro"

x-db: &db
  image: "${IMAGE_MYSQL:?}"
  environment:
    - "MYSQL_DATABASE=${MYSQL_DATABASE:?}"
    - "MYSQL_USER=${MYSQL_USER:?}"
    - "MYSQL_PASSWORD=${MYSQL_PASSWORD:?}"
    - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?}"
  ports:
    - "${MYSQL_PORT:?}:3306"

# application
services:
  app:
    <<: *app
    depends_on: [db]
  app-test:
    <<: *app
    depends_on: [db-test]

  web:
    <<: *web

  db:
    <<: *db
    volumes:
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - db-data:/var/lib/mysql:rw
  db-test:
    <<: *db
    ports:
      - "${MYSQL_TEST_PORT:?}:3306"
    volumes:
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - db-test-data:/var/lib/mysql:rw

volumes:
  db-data: {}
  db-test-data: {}
