version: '3.7'

services:
  app:
    volumes:
      - ../../../:/app:rw
    depends_on:
      - db

  web:
    volumes:
      - ../../../public:/app/public:ro

  db:
    image: "mysql:${MYSQL}"
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./db/mysql.cnf:/etc/mysql/conf.d/my.cnf:ro
      - db-data:/var/lib/mysql:rw

volumes:
  db-data: {}
